# Generated by Django 5.0.2 on 2024-03-29 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learningapp', '0005_inprogresscourse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CollectionCourse',
        ),
    ]
