# Generated by Django 5.0.2 on 2024-03-30 18:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learningapp', '0007_completedcourse1_delete_completedcourse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompletedCourse1',
            new_name='CompletedCourse',
        ),
    ]
